version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "selenium-csharp"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      xunit:
        patterns:
          - xunit
          - xunit.analyzers
          - xunit.runner.visualstudio
      selenium:
        patterns:
          - Selenium.WebDriver
          - Selenium.WebDriver.ChromeDriver
