pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - puppeteer/*
    - puppeteer.yml
    exclude:
    - puppeteer/README.md

steps:

- bash: |
    sudo sysctl -w kernel.unprivileged_userns_clone=1
  displayName: Enable user namespace cloning

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: Install Yarn 1.12.3
  inputs:
    versionSpec: 1.12.3

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: yarn install
  inputs:
    Arguments: install
    ProjectDirectory: puppeteer

- bash: |
    cd puppeteer
    node ./node_modules/jasmine/bin/jasmine.js
  displayName: yarn test
