pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - puppeteer/*
    - puppeteer.yml
    exclude:
    - puppeteer/README.md

steps:

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: Install Yarn 1.22.4
  inputs:
    versionSpec: 1.22.4

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: yarn install
  inputs:
    Arguments: install
    ProjectDirectory: puppeteer

- bash: |
    sudo apt-get update
    sudo apt-get install -y libgbm1
  displayName: Install libgbm1 (required by Puppeteer 3)

- bash: |
    yarn test-ci
  env:
    GABO_GOODREADS_SIGNINCREDENTIALS_EMAILADDRESS: $(Goodreads.SignInCredentials.EmailAddress)
    GABO_GOODREADS_SIGNINCREDENTIALS_PASSWORD: $(Goodreads.SignInCredentials.Password)
    GABO_SCREENSHOTS_ABSOLUTEPATH: $(Build.StagingDirectory)
    MOCHA_FILE: '$(Common.TestResultsDirectory)/test-results.xml'
  displayName: yarn test
  workingDirectory: puppeteer

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'FailedTestsScreenshots'
    targetPath: $(Build.StagingDirectory)
  condition: failed()
  displayName: Upload screenshot(s) after test(s) failure

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.xml'
    testResultsFormat: 'JUnit'
    searchFolder: $(Common.TestResultsDirectory)
    publishRunAttachments: true
  condition: succeededOrFailed()
  displayName: Publish tests results
