pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - puppeteer/*
    - puppeteer.yml
    exclude:
    - puppeteer/README.md

steps:

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: Install Yarn 1.12.3
  inputs:
    versionSpec: 1.12.3

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: yarn install
  inputs:
    Arguments: install
    ProjectDirectory: puppeteer

- bash: |
    cd puppeteer
    yarn test
  env:
    GABO_GITHUB_SIGNINCREDENTIALS_USERNAME: $(GitHub.SignInCredentials.Username)
    GABO_GITHUB_SIGNINCREDENTIALS_PASSWORD: $(GitHub.SignInCredentials.Password)
    GABO_SCREENSHOTS_ABSOLUTEPATH: $(Build.StagingDirectory)
  displayName: yarn test

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'FailedTestsScreenshots'
    targetPath: $(Build.StagingDirectory)
  condition: failed()
  displayName: Upload screenshot(s) after test(s) failure
