pool:
  vmImage: ubuntu-20.04

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - puppeteer/*
    - puppeteer.yml
    exclude:
    - puppeteer/README.md

pr:
  paths:
    include:
    - puppeteer/*
    - puppeteer.yml
    exclude:
    - puppeteer/README.md

steps:

- bash: |
    yarn install
  displayName: 'yarn install'
  workingDirectory: puppeteer

- bash: |
    yarn test-ci
  env:
    GABO_GOODREADS_SIGNINCREDENTIALS_EMAILADDRESS: $(Goodreads.SignInCredentials.EmailAddress)
    GABO_GOODREADS_SIGNINCREDENTIALS_PASSWORD: $(Goodreads.SignInCredentials.Password)
    GABO_SCREENSHOTS_ABSOLUTEPATH: $(Build.StagingDirectory)
    MOCHA_FILE: '$(Common.TestResultsDirectory)/test-results.xml'
  displayName: yarn test
  workingDirectory: puppeteer

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'FailedTestsScreenshots'
    targetPath: $(Build.StagingDirectory)
  condition: failed()
  displayName: Upload screenshot(s) after test(s) failure

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.xml'
    testResultsFormat: 'JUnit'
    searchFolder: $(Common.TestResultsDirectory)
    publishRunAttachments: true
  condition: succeededOrFailed()
  displayName: Publish tests results
