pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - selenium-csharp/*
    - selenium-csharp.yml
    exclude:
    - selenium-csharp/README.md

steps:

- bash: |
    cd selenium-csharp/src/GitHubSelenium
    dotnet test --logger trx --results-directory $(Common.TestResultsDirectory) --output $(Build.StagingDirectory)
  env:
    GitHub__SignInCredentials__Password: $(GitHub.SignInCredentials.Password)
    GitHub__SignInCredentials__Username: $(GitHub.SignInCredentials.Username)
  displayName: Run tests

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'FailedTestsScreenshots'
    targetPath: '$(Build.StagingDirectory)/screenshots'
  condition: failed()
  displayName: Upload screenshot(s) after test(s) failure

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.trx'
    testResultsFormat: 'VSTest'
    searchFolder: $(Common.TestResultsDirectory)
    publishRunAttachments: true
  condition: succeededOrFailed()
  displayName: Publish tests results
