pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - selenium-csharp/*
    - selenium-csharp.yml
    exclude:
    - selenium-csharp/README.md

steps:

- bash: |
    cd selenium-csharp/src/GitHubSelenium
    dotnet test --output $(Build.StagingDirectory)
  env:
    GitHub__SignInCredentials__Password: $(GitHub.SignInCredentials.Password)
    GitHub__SignInCredentials__Username: $(GitHub.SignInCredentials.Username)
  displayName: Run tests

steps:
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'FailedTestsScreenshots'
    targetPath: $(Build.StagingDirectory)
  condition: failed()
  displayName: Upload screenshot(s) after test failure
