pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - selenium-csharp/*
    - selenium-csharp.yml
    exclude:
    - selenium-csharp/README.md

steps:

- bash: |
    cd selenium-csharp
    dotnet test
