name: Puppeteer

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/puppeteer.yml
      - 'puppeteer/**'
      - '!puppeteer/README.md'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/puppeteer.yml
      - 'puppeteer/**'
      - '!puppeteer/README.md'
  schedule:
    - cron: '0 20 * * 0-4'

jobs:
  tests:
    name: Run Puppeteer UI tests
    runs-on: ubuntu-22.04
    env:
      GABO_SCREENSHOTS_ABSOLUTEPATH: ${{ github.workspace }}/puppeteer/screenshots
    defaults:
      run:
        working-directory: puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn install
      - name: yarn test-ci
        run: yarn test-ci
        env:
          GABO_REDDIT_SIGNINCREDENTIALS_USERNAME: ${{ secrets.USERNAME }}
          GABO_REDDIT_SIGNINCREDENTIALS_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Upload screenshot(s) after test(s) failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ env.GABO_SCREENSHOTS_ABSOLUTEPATH }}
          if-no-files-found: error
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: puppeteer/test-results
          if-no-files-found: error
