name: Selenium C#

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/selenium-csharp.yml
      - '.vscode/**'
      - 'selenium-csharp/**'
      - '!selenium-csharp/README.md'

jobs:
  tests:
    name: Run Selenium C# UI tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Handling skipped but required check, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"